### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
     'this is a very very very long sentence']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good',
 'this is a very very very long sentence']

In [5]:
### Vocabulary size
voc_size=10

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1, 3, 7, 5], [1, 3, 7, 3], [1, 6, 7, 5], [1, 8, 8, 4, 6], [1, 8, 8, 4, 9], [7, 1, 8, 7, 9], [8, 2, 2, 4], [6, 4, 8, 1, 1, 1, 4, 4]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=4
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[1 3 7 5]
 [1 3 7 3]
 [1 6 7 5]
 [8 8 4 6]
 [8 8 4 9]
 [1 8 7 9]
 [8 2 2 4]
 [1 1 4 4]]


In [10]:
dim=5

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 10)             100       
Total params: 100
Trainable params: 100
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.03601068 -0.03204801 -0.04738252  0.02014679  0.02994459
   -0.03868296 -0.02591406  0.04970111 -0.04081966 -0.00638343]
  [-0.00804851 -0.04305918  0.02911815 -0.00342906 -0.03843765
    0.0058141  -0.04455216 -0.00474739 -0.02467592 -0.01661383]
  [-0.02967339 -0.03987337  0.0428537   0.04871808  0.04269589
    0.01329077 -0.03380141  0.03816352 -0.03190966 -0.04730816]
  [-0.03868271 -0.02149376  0.01174919 -0.01049298 -0.02043855
    0.04200822  0.0015616  -0.02681918  0.04027155  0.04479493]]

 [[-0.03601068 -0.03204801 -0.04738252  0.02014679  0.02994459
   -0.03868296 -0.02591406  0.04970111 -0.04081966 -0.00638343]
  [-0.00804851 -0.04305918  0.02911815 -0.00342906 -0.03843765
    0.0058141  -0.04455216 -0.00474739 -0.02467592 -0.01661383]
  [-0.02967339 -0.03987337  0.0428537   0.04871808  0.04269589
    0.01329077 -0.03380141  0.03816352 -0.03190966 -0.04730816]
  [-0.00804851 -0.04305918  0.02911815 -0.00342906 -0.03843765
    0.0058141  -0.04455216 -0.00474739 -0.0246

In [14]:
embedded_docs[0]

array([1, 3, 7, 5])

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.03601068 -0.03204801 -0.04738252  0.02014679  0.02994459 -0.03868296
  -0.02591406  0.04970111 -0.04081966 -0.00638343]
 [-0.00804851 -0.04305918  0.02911815 -0.00342906 -0.03843765  0.0058141
  -0.04455216 -0.00474739 -0.02467592 -0.01661383]
 [-0.02967339 -0.03987337  0.0428537   0.04871808  0.04269589  0.01329077
  -0.03380141  0.03816352 -0.03190966 -0.04730816]
 [-0.03868271 -0.02149376  0.01174919 -0.01049298 -0.02043855  0.04200822
   0.0015616  -0.02681918  0.04027155  0.04479493]]


In [16]:
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(model.predict(embedded_docs)[0]))

[[ 1.          0.09362677  0.48320937 -0.40905178]
 [ 0.09362677  1.0000001   0.4277816   0.12175389]
 [ 0.48320937  0.4277816   1.         -0.24823035]
 [-0.40905178  0.12175389 -0.24823035  1.0000001 ]]


In [17]:
sent = 'Man and women both are equally important in the society'
print(cosine_similarity(model.predict(sent)))

IndexError: list index out of range