### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
      'This is a large sentence with many words contained within it without extra efforts']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good',
 'This is a large sentence with many words contained within it without extra efforts']

In [ ]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[851, 7225, 8339, 8175], [851, 7225, 8339, 3028], [851, 1409, 8339, 5100], [6952, 1825, 3357, 4272, 4004], [6952, 1825, 3357, 4272, 9505], [6705, 851, 4952, 8339, 906], [7797, 6300, 2323, 4272], [1477, 6140, 3357, 4780, 1224, 2555, 7550, 906, 1149, 7794, 5426, 8083, 4233, 2232]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre')#,maxlen=sent_length)
# embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0    0    0    0    0  851 7225 8339 8175]
 [   0    0    0    0    0    0    0    0    0    0  851 7225 8339 3028]
 [   0    0    0    0    0    0    0    0    0    0  851 1409 8339 5100]
 [   0    0    0    0    0    0    0    0    0 6952 1825 3357 4272 4004]
 [   0    0    0    0    0    0    0    0    0 6952 1825 3357 4272 9505]
 [   0    0    0    0    0    0    0    0    0 6705  851 4952 8339  906]
 [   0    0    0    0    0    0    0    0    0    0 7797 6300 2323 4272]
 [1477 6140 3357 4780 1224 2555 7550  906 1149 7794 5426 8083 4233 2232]]


In [ ]:
dim=20

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 20)             200000    
Total params: 200,000
Trainable params: 200,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 0.04863762 -0.02495554  0.03715121  0.0251151  -0.03735955
    0.03965921  0.01000107 -0.02534595 -0.02614255 -0.02239167]
  [ 0.04863762 -0.02495554  0.03715121  0.0251151  -0.03735955
    0.03965921  0.01000107 -0.02534595 -0.02614255 -0.02239167]
  [ 0.04863762 -0.02495554  0.03715121  0.0251151  -0.03735955
    0.03965921  0.01000107 -0.02534595 -0.02614255 -0.02239167]
  [ 0.04863762 -0.02495554  0.03715121  0.0251151  -0.03735955
    0.03965921  0.01000107 -0.02534595 -0.02614255 -0.02239167]
  [-0.02131879 -0.02895187  0.02804314 -0.03309541 -0.00208266
   -0.03400367  0.00082622 -0.02375109 -0.01882608  0.02259849]
  [ 0.01002611 -0.01786288  0.03358186  0.03705904 -0.03820837
    0.03045113  0.04941418 -0.00218815 -0.04568384 -0.0288983 ]
  [ 0.01940948  0.01333512 -0.01999121 -0.03377332 -0.03855071
   -0.04551054 -0.01688695  0.03054967  0.02708993 -0.01705335]
  [-0.03716124 -0.02101346 -0.02265024 -0.03732961  0.04635492
    0.00667496 -0.04086614  0.00782358 -0.021369

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,  851, 7225, 8339, 8175], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 0.00264085  0.0388321   0.03712317  0.03566848  0.01867634  0.0449524
   0.03126687  0.01944491  0.00115735 -0.0165735   0.0339505  -0.01073737
   0.02871448  0.03949795  0.02239156  0.03571687 -0.0252085  -0.04307188
   0.04385756  0.00337149]
 [ 0.00264085  0.0388321   0.03712317  0.03566848  0.01867634  0.0449524
   0.03126687  0.01944491  0.00115735 -0.0165735   0.0339505  -0.01073737
   0.02871448  0.03949795  0.02239156  0.03571687 -0.0252085  -0.04307188
   0.04385756  0.00337149]
 [ 0.00264085  0.0388321   0.03712317  0.03566848  0.01867634  0.0449524
   0.03126687  0.01944491  0.00115735 -0.0165735   0.0339505  -0.01073737
   0.02871448  0.03949795  0.02239156  0.03571687 -0.0252085  -0.04307188
   0.04385756  0.00337149]
 [ 0.00264085  0.0388321   0.03712317  0.03566848  0.01867634  0.0449524
   0.03126687  0.01944491  0.00115735 -0.0165735   0.0339505  -0.01073737
   0.02871448  0.03949795  0.02239156  0.03571687 -0.0252085  -0.04307188
   0.04385756  0.00337149]
 [ 0.046

In [ ]:
list(embedded_docs)

[array([   0,    0,    0,    0,  851, 7225, 8339, 8175], dtype=int32),
 array([   0,    0,    0,    0,  851, 7225, 8339, 3028], dtype=int32),
 array([   0,    0,    0,    0,  851, 1409, 8339, 5100], dtype=int32),
 array([   0,    0,    0, 6952, 1825, 3357, 4272, 4004], dtype=int32),
 array([   0,    0,    0, 6952, 1825, 3357, 4272, 9505], dtype=int32),
 array([   0,    0,    0, 6705,  851, 4952, 8339,  906], dtype=int32),
 array([   0,    0,    0,    0, 7797, 6300, 2323, 4272], dtype=int32)]

In [ ]:
#GLoVe and Word2vec